# Generated by Django 6.0.1 on 2026-01-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('user', 'user'), ('Garages', 'Garages')], max_length=30)),
                ('phone', models.BigIntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
