# Generated by Django 6.0.1 on 2026-01-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivecareapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('massage', models.TextField()),
            ],
        ),
    ]
