# Generated by Django 5.2.7 on 2026-01-25 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivecareapp', '0002_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('service_price', models.FloatField()),
                ('service_desc', models.TextField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivecareapp.category')),
                ('garage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivecareapp.registertable')),
            ],
        ),
        migrations.DeleteModel(
            name='contactpage',
        ),
    ]
