# Generated by Django 6.0.1 on 2026-01-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivecareapp', '0003_category_services_delete_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('massage', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='registertable',
            new_name='logintable',
        ),
    ]
