# Generated by Django 6.0.1 on 2026-01-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivecareapp', '0003_category_rename_registertable_logintable_services'),
        ('drivecareapp', '0004_contactpage_rename_registertable_logintable'),
    ]

    operations = [
    ]
